baseurl = "https://mifistor.github.io/"
languageCode = "ru"
title = "mifistor.ru"
theme = "beautifulhugo"
disqusShortname = "mifistor"
googleAnalytics = "UA-93024367-1"
enableInlineShortcodes = true

[Params]
#  Author = "Mikhail Dymskov"
  subtitle = "персональный блог"
  #logo = "img/avatar-icon.png"
  #favicon = "img/favicon.ico"
  #commit = false

[Author]
  name = "Михаил Дымсков"
  email = "mifistor@gmail.com"
  facebook = "mifistor"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "mifistor"
  twitter = "mifistor"

[[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Обо мне"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Курсы для крестных родителей онлайн"
    url = "/page/courses/"
    weight = 4

#[[menu.main]]
#    identifier = "samples"
#    name = "Samples"
#    weight = 2
#
#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "/post/2016-03-08-code-sample"
#
#[[menu.main]]
#    parent = "samples"
#    name = "Test Markdown"
#    url = "/post/2015-02-20-test-markdown"
#
#[[menu.main]]
#    name = "Tags"
#    url = "/tags"
#    weight = 3
